### ISSUE TITLE
Avaloniaui support

### ISSUE THREAD

**Issue by NeverMorewd** [Cysharp/ObservableCollections#46]
https://github.com/AvaloniaUI/Avalonia/discussions/15623
https://github.com/AvaloniaUI/Avalonia/issues/15607

**Comment by djeikyb** [comment]
Is this likely to need a change in Avalonia? Or solved like in [R3.Avalonia](https://github.com/Cysharp/R3/blob/1.2.2/src/R3.Avalonia/ObserveOnExtensions.cs)?

**Comment by neuecc** [comment]
ObservableCollections(ToNotifyCollectionChanged()) are not dependent on any particular platform, and only implement INotifyCollectionChanged.
If there are any problems with the binding, I don't think there is anything we can do about it.

**Comment by NeverMorewd** [comment]
> ObservableCollections(ToNotifyCollectionChanged()) are not dependent on any particular platform, and only implement INotifyCollectionChanged. If there are any problems with the binding, I don't think there is anything we can do about it.

However, in wpf sampe

```
// WPF simple sample.

ObservableList<int> list;
public INotifyCollectionChangedSynchronizedView<int> ItemsView { get; set; }

public MainWindow()
{
    InitializeComponent();
    this.DataContext = this;

    list = new ObservableList<int>();
    ItemsView = list.CreateView(x => x).ToNotifyCollectionChanged();

    **BindingOperations.EnableCollectionSynchronization**(ItemsView, new object()); // for ui synchronization safety of viewmodel
}

protected override void OnClosed(EventArgs e)
{
    ItemsView.Dispose();
}
```

**BindingOperations.EnableCollectionSynchronization** is a static method in "System.Windows.Data" ,there is no similar implementation in the avaloniaui.

**Comment by neuecc** [comment]
As for synchronization, ObservableCollections are not the kind of thing that handles it, so it's just a matter of doing the appropriate thing in each UI framework.
The code is just saying that it is easier to do it that way in WPF.

**Comment by NeverMorewd** [comment]
> As for synchronization, ObservableCollections are not the kind of thing that handles it, so it's just a matter of doing the appropriate thing in each UI framework.
> 
> The code is just saying that it is easier to do it that way in WPF.

got it

**Comment by djeikyb** [comment]
I guess maybe I have a discussion question more than an issue to raise. If I'm using R3 (because it feels intuitive coming from vuejs, and has nice things like debounce), and now I want to bind repeating data controls like [ListBox](https://docs.avaloniaui.net/docs/reference/controls/listbox), should I be reaching for ObservableCollections? Or am I totally misunderstanding what to reach for?

As far as _how_ to use ObservableCollections with Avalonia instead of _should_ I.. My experience level is total noobie, I come from vuejs. But here goes!

Personally, I can't see why binding to a repeating control like ListBox doesn't work. When I attach a debugger, I always see that I'm on something Rider names "Main Thread", which I assume is the ui thread. I called `Dispatcher.UIThread.Invoke` and stuck a breakpoint in my callback and.. it says "Main Thread".

On the Avalonia side, they say the problem with using ObservableCollections is that the events aren't being raised on the ui thread. On the R3 side, I see a whole R3.Avalonia classlib that looks designed to solve "make sure events are raised on the ui thread". Here on the ObservableCollections side, I'm hearing "not solveable here". I was looking through the [DynamicData](https://github.com/reactivemarbles/DynamicData) code and I see a lot of stuff like `ObserveOnDispatcher`.

**Comment by djeikyb** [comment]
For anyone else scrolling through tryna make sense.. after a long weekend of sleep and extra-vocational distractions, it was immediately obvious that for my short list box of options, extending System.Collections.ObjectModel.ObservableCollection[T] would do just fine:

```cs
using System;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Example;

public class MutableObservableCollection<T> : ObservableCollection<T>
{
    public void ForEach(Action<T> action)
    {
        foreach (var item in Items)
        {
            action.Invoke(item);
        }

        base.OnCollectionChanged(new NotifyCollectionChangedEventArgs(NotifyCollectionChangedAction.Reset));
    }
}
```

**Comment by supermomonga** [comment]
https://github.com/AvaloniaUI/Avalonia/issues/16609#issuecomment-2272221145

According to this, AvaloniaUI requires not only `INotifyCollectionChanged` but `IList`, by design.
So I believe it's not be possible to use ObservableCollections with AvaloniaUI unless AvaloniaUI changes their design to require only `INotifyCollectionChanged` or ObservableCollections side provides a another type of View class that implements `INotifyCollectionChanged` and `IList`.

**Comment by neuecc** [comment]
v2.1.3, I've implemented `IColllectionEventDispatcher` mechanism.
No longer need `EnableCollectionSynchronization` and deleted in ReadMe sample.
However, it seems that the main topic of discussion here was not about UI thread safety in the first place...

**Comment by supermomonga** [comment]
@neuecc Thanks! I think now I can use [AvaloniaSynchronizationContext](https://github.com/AvaloniaUI/Avalonia/blob/master/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs) easily.

> However, it seems that the main topic of discussion here was not about UI thread safety in the first place...

Yes, as I mentioned above, the problem is that AvaloniaUI requires `IList` implementation for collection binding.

As my understand, ObservableCollections only provides `IReadOnlyCollection` implementation for `INotifiCollectionChanged` implementation class.

Can I hear your opinion about this? Are you comfortable to add `IList` + `INotifyCollectionChanged` version of view class to ObservableCollections? or, Avalonia should works with any `INotifyCollectionChanged` implementations?

**Comment by neuecc** [comment]
Thanks for the detailed information, it helped me understand it better!
I also placed the Avalonia sandbox project in the repository and checked it out.

In v1.2.0, the NotifyCollectionChangedCollection from ObservableList.View now implements `IList`.
This should have enabled support for AvaloniaUI.
(There is a possibility that the behavior will break if you attach other filters, but I will verify this later or think of other countermeasures.)

**Comment by supermomonga** [comment]
@neuecc Thanks a lot!!
