### ISSUE TITLE
Serializable class for Unity

### ISSUE THREAD

**Issue by nyoro-wrl** [Cysharp/ObservableCollections#47]
- `SerializableObservableList<T>`
- `SerializableObservableDictionary<TKey, TValue>`
- `SerializableObservableHashSet<T>`
- `SerializableObservableQueue<T>`
- `SerializableObservableStack<T>`
- `SerializableObservableRingBuffer<T>`
- `SerializableObservableFixedSizeRingBuffer<T>`

**Comment by neuecc** [comment]
Not in the plan.

**Comment by jannesiera** [comment]
@neuecc what would it take to implement these? I'd love to use reactive collections directly from the editor.

**Comment by neuecc** [comment]
This is also same for regular Dictionaries, isn't it?
Would the workaround there be to implement ISerializationCallbackReceiver in an inherited class?
If so, we should probably do the same thing - while it might be slightly less efficient, it shouldn't be too noticeable when used in the Editor.

**Comment by jannesiera** [comment]
Thanks for the quick response @neuecc !

Since the original comment was a very short "not in the plan" I assumed this was because there were some caveats making this difficult (especially because we do have `SerializableReactiveProperty`). However, after my comment I did go and try out exactly what you are proposing and it seems to work without a hitch.

Here is my implementation (I just did `SerializableObservableList<T>` but the other ones should be just as easy):

```
    [Serializable]
    public class SerializableObservableList<T> : ObservableList<T>, ISerializationCallbackReceiver
    {
        [SerializeField]
        private List<T> data = new();

        public void OnBeforeSerialize()
        {
            data = this.ToList();
        }

        public void OnAfterDeserialize()
        {
            Clear();
            AddRange(data);
        }
    }
```
